config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'games#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end
end

  get 'welcome/index'
  
  resources :games do
    member do
      get :join
      get :set_options
    end
  end
  resources :options, only: [:create, :destroy]
  # get 'games, to: 'games#create'

  # get '/patients/:id', to: 'patients#show', as: 'patient' 

  # root 'frank#index' RIP: 12-11-14
  
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base

belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
 
  has_many :messages, dependent: :destroy
 
  validates_uniqueness_of :sender_id, :scope => :recipient_id
 
  scope :involving, -> (user) do
    where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  end
 
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end


  
end

app/models/game.rb
class Game < ActiveRecord::Base

  has_many :user_games, dependent: :destroy
  has_many :users, through: :user_games
  has_many :options, through: :users
  # before_destroy :destroy_options

  def option_limit_met(user)
    unless self.users.find(user.id).option.nil? 
      return true
    end
  end

  def self.num_users
    2
  end

  def user_limit_met
    if self.users.count >= Game.num_users
      return true
    #errors.add(:user_id, 'Error - Game full')
    end
  end
  
  def destroy_options
    options.map{|o| o.destroy}
  end

  def options_for user
    UserGame.find_by(user_id: user, game_id: self.id).options
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :user_game

  # after_create :check_ready_status?
  after_create :start_game


  def players_ready?
    players = self.user_game.game.user_games
    options_ready = players.map{ |player| player.options.any? }
    options_ready.size == Game.num_users && !options_ready.include?(false)
  end


  def start_game
    if players_ready?
      game = self.user_game.game
      game.active = true
      game.save
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  has_one :user_game
  has_many :games, through: :user_game
  has_many :options, through: :user_game

  def game
    self.games.first
  end

  def option
    self.options.first
  end


  def in_game?
    UserGame.where(user_id: self.id).any?
  end

  def can_join_game?
    UserGame.where(user_id: self.id).any?
  end

  def in_this_game? game
    UserGame.where(user_id: self.id, game_id: game).any?
  end

  def current_game
    self.games.first rescue nil
  end

end

# unless current_user.in_game
#   join game
# else
#   notice
# end

app/models/user_game.rb
class UserGame < ActiveRecord::Base
  has_many :options, dependent: :destroy
  belongs_to :user
  belongs_to :game

  validates :user_id, uniqueness: {scope: :game_id, message: "You already joined this game."} 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end


end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  class ConversationsController < ApplicationController
  before_filter :authenticate_user!
 
  layout false
 
  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id],params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
 
    render json: { conversation_id: @conversation.id }
  end
 
  def show
    @conversation = Conversation.find(params[:id])
    @reciever = interlocutor(@conversation)
    @messages = @conversation.messages
    @message = Message.new
  end
 
  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
 
  def interlocutor(conversation)
    current_user == conversation.recipient ? conversation.sender : conversation.recipient
  end
end
end

app/controllers/frank_controller.rb
class FrankController < ApplicationController
  before_action :authenticate_user!, except: [:index, :edit]
  def index
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id]) 

    if !current_user.current_game == @game
      redirect_to games_path
    else
      if @game.options_for(current_user).empty?
        redirect_to set_options_game_path(@game)
      elsif !@game.active
        flash[:error] = "Waiting on other users."
        redirect_to games_path
      end
    end

        


    # redirect_to games_path unless current_user.in_this_game?(@game)
  end

  def set_options
    @game = Game.find(params[:id]) 
    @user_game = UserGame.find_by(game: @game, user: current_user)
    if @game.active
      redirect_to games
    end
  end
  
  def join
    @game = Game.find(params[:id])

      if @game.user_limit_met
        flash[:error] = "Game is full!"
        redirect_to :back 
      else
         if !current_user.in_game? 
            @user_game = UserGame.create(user_id: current_user.id, game_id: @game.id)
            flash[:success] = "#{@game.title} was joined"
            redirect_to @user_game.game     
         else
            redirect_to game_path(current_user.current_game)
          end
        end

  end


  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      flash[:success] = "Added game."
      redirect_to games_path
    else
      flash[:error] = "There was a problem adding that game."
      render action: :new
    end
  end

private
  

  def game_params
    params[:game].permit(:title)
  end

    # if current_user.can_join_game?
    #   if current_user.current_game.active
    #     redirect_to game_path(current_user.current_game)
    #   else
    #     redirect_to set_options_game_path(current_user.current_game)
    #   end
    # else


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
 
  def create
    @conversation = Conversation.find(params[:conversation_id])
    @message = @conversation.messages.build(message_params)
    @message.user_id = current_user.id
    @message.save!
 
    @path = conversation_path(@conversation)
  end
 
  private
 
  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController



  def create
    puts "TEST"
    puts params[:option][:user_game_id]
    @game = UserGame.find(params[:option][:user_game_id]).game
    @option = Option.new(option_params)


      if @game.option_limit_met(current_user)

        flash[:error] = "You've already added an option."
        redirect_to :back
      else
        @option.save
        flash[:success] = "You added an option!"
        redirect_to :back
      
      end   
  end
  def destroy
    @option = Option.find(params[:id])
    @option.destroy
  end

 private
  def option_params
    params[:option].permit(:description, :user_game_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def self_or_other(message)
    message.user == current_user ? "self" : "other"
  end
 
  def message_interlocutor(message)
    message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipient
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/conversations/show.html.erb
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>
 
    <h1><%= @reciever.name %> </h1>
  </div>
  <div class="chatboxoptions">
    <%= link_to "<i class='fa  fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='fa  fa-times'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
  <br clear="all"/>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<div class="chatboxinput">
  <%= form_for([@conversation, @message], :remote => true, :html => {id: "conversation_form_#{@conversation.id}"}) do |f| %>
      <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @conversation.id %>
  <% end %>
</div>
 
<%= subscribe_to conversation_path(@conversation) %>

app/views/frank/index.html.erb
franks page

app/views/games/_form.html.erb
<% if @game.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

  <ul>
    <% @game.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


<%= f.label :title %>
<%= f.text_field :title %>

<%= f.submit "Save" %>

app/views/games/index.html.erb
<%@games.each do |game| %>
  <%= game.title %> | 
  <% if current_user.game == game %>
    <%= link_to "Go to Game", game_path(game) %>
  <% else %>
    <%= link_to "Join this Game", join_game_path(game) %>
  <% end %>
  <br>
  <br>
<% end %>

app/views/games/join.html.erb
You just joined <%=@game.title%>


<%=@user_game.errors.messages%>

app/views/games/new.html.erb
<h1> Add Game</h1>
<%= form_for @game do |f| %>
  <% if @game.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

  <ul>
    <% @game.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


<%= f.label :title %>
<%= f.text_field :title %>

<%= f.submit "Save" %>
<% end %>

app/views/games/set_options.html.erb
<%= form_for Option.new, url: options_path, html: {multipart: true} do |f| %>
  Option: 
  <% if current_user.options.empty? %>
  <%= f.text_field :description %>
  <% else %>
  <%= f.text_field :description, value: current_user.
      option.description  %>
  <% end %>
  <%= f.hidden_field :user_game_id, value: @user_game.id %>
  <%= f.submit 'Ready' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Madmeeting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

     <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or 
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>

<% if flash[:error] %>
  <p class="error"><%= flash[:error] %></p>
<% end %>

<% if flash[:success] %>
  <p class="success"><%= flash[:success] %></p>
<% end %>
       <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/messages/_message.html.erb
<li class="<%=  self_or_other(message) %>">
  <div class="avatar">
    <img src="http://placehold.it/50x50" />
  </div>
  <div class="chatboxmessagecontent">
    <p><%= message.body %></p>
    <time datetime="<%= message.created_at %>" title="<%= message.created_at.strftime("%d %b  %Y at %I:%M%p") %>">
      <%= message_interlocutor(message).name %> • <%= message.created_at.strftime("%H:%M %p") %>
    </time>
  </div>
</li>

app/views/messages/create.js.erb
<% publish_to @path do %>
    var id = "<%= @conversation.id %>";
    var chatbox = $("#chatbox_" + id + " .chatboxcontent");
    var sender_id = "<%= @message.user.id %>";
    var reciever_id = $('meta[name=user-id]').attr("content");
 
    chatbox.append("<%= j render( partial: @message ) %>");
    chatbox.scrollTop(chatbox[0].scrollHeight);
 
    if(sender_id != reciever_id){
      chatBox.chatWith(id);
        chatbox.children().last().removeClass("self").addClass("other");        
      chatbox.scrollTop(chatbox[0].scrollHeight);
        chatBox.notify();
    }
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>